(in-package #:kslgui)

(export 'fill-rectangle)
(declaim (ftype (function (ui double-float double-float double-float double-float (unsigned-byte 32))
                          (values &optional))
                fill-rectangle))
(defun fill-rectangle (ui x y w h color)
  (let ((rect (alloc-blend2d-rect ui)))
    (setf (%blend2d:rect.x rect) x)
    (setf (%blend2d:rect.y rect) y)
    (setf (%blend2d:rect.w rect) w)
    (setf (%blend2d:rect.h rect) h)
    (%blend2d:context-fill-rect-d-rgba32 (layer-context (current-layer ui)) rect color)
    (free-blend2d-rect ui rect))
  (values))
