(in-package #:kslgui)

(export 'fill-rectangle*)
(declaim (ftype (function (ui double-float double-float double-float double-float &optional (or null (unsigned-byte 32)))
                          (values &optional))
                fill-rectangle*))
(defun fill-rectangle* (ui x y w h &optional color)
  (let ((rect (alloc-blend2d-rect ui)))
    (setf (%blend2d:rect.x rect) x)
    (setf (%blend2d:rect.y rect) y)
    (setf (%blend2d:rect.w rect) w)
    (setf (%blend2d:rect.h rect) h)
    (if color
        (%blend2d:context-fill-rect-d-rgba32 (layer-context (current-layer ui)) rect color)
        (%blend2d:context-fill-rect-d (layer-context (current-layer ui)) rect))
    (free-blend2d-rect ui rect))
  (values))

(export 'fill-rectangle)
(declaim (ftype (function (ui real real real real &optional (or null (unsigned-byte 32)))
                          (values &optional))
                fill-rectangle))
(defun fill-rectangle (ui x y w h &optional color)
  (fill-rectangle* ui
                   (coerce x 'double-float)
                   (coerce y 'double-float)
                   (coerce w 'double-float)
                   (coerce h 'double-float)
                   color))
