; (in-package #:kishka.gui)

; (defun w-slider-impl ())

; (defmacro w-slider (&key (value 0.0) (min 0.0) (max 1.0) (type 'single-float) (on-changed nil)
;                          (track-height 3.0) (show-value t)
;                          (track-color #xFFFFFFFF)
;                          (track-color.before nil)
;                          (track-color.progress nil)
;                          (track-color.after nil)
;                          (thumb-color #xFFFFFFFF)
;                          (thumb-color.hover nil)
;                          (thumb-color.active nil)
;                          (thumb-size 5.0)
;                          (thumb-size.hover nil)
;                          (thumb-size.active nil)
;                          (thumb-shape :square)
;                          (style nil))
;     `(make-widget* :style ,style))
